apiVersion: v2
name: element-call
description: A Helm chart for element_call
type: application
version: 0.1.0
appVersion: "v0.5.15"

dependencies:
- name: livekit-server
  version: "1.5.3"
  repository: "https://helm.livekit.io"
  condition: livekit-server.enabled