apiVersion: v2
name: element-call
description: A Helm chart for element_call
type: application
version: 0.1.6
appVersion: "v0.5.15"

dependencies:
  - name: livekit-server
    version: "1.5.3"
    repository: "https://helm.livekit.io"
    condition: livekit-server.enabled
  - name: egress
    version: "1.8.1"
    repository: "https://helm.livekit.io"
    condition: egress.enabled
  - name: redis
    version: ^18.17.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
