---
apiVersion: v1
kind: ConfigMap
metadata:
  name: { { include "element_call.fullname" . } }
  labels: { { - include "element_call.labels" . | nindent 4 } }
data:
  config.json: |
    {
      "default_server_config": {
        "m.homeserver": {
          "base_url": "{{ .Values.element_call.config.homeserver.base_url }}",
          "server_name": "{{ .Values.element_call.config.homeserver.server_name }}"
        }
      },
      "eula": "{{ .Values.element_call.config.eula }}",
      "livekit": {
        livekit_service_url: "{{ .Values.element_call.config.livekit.livekit_service_url }}"
      }
    }
