---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "element_call.fullname" . }}
  labels:
    {{- include "element_call.labels" . | nindent 4 }}
spec:
  type: {{ .Values.element_call.service.type }}
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "element_call.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "element_call.livekit_mgmt_name" . }}
  labels:
    {{- include "element_call.livekit_mgmt.labels" . | nindent 4 }}
spec:
  type: {{ .Values.livekit_mgmt.service.type }}
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "element_call.livekit_mgmt.selectorLabels" . | nindent 4 }}
